name: Build Everything TGW

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-binaries to build: v0.1.0'
        default: 'v0.1.0'
        required: true
        type: string

permissions:
  contents: write

jobs:          
  build_release_cuda_windows:
    name: CUDA Windows
    uses: ./.github/workflows/build-portable-release-cuda.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:windows-2019'

  build_release_cuda_linux:
    name: CUDA Linux
    uses: ./.github/workflows/build-portable-release-cuda.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:ubuntu-22.04'

  build_release_cpu_windows:
    name: CUDA Windows
    uses: ./.github/workflows/build-portable-release.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:windows-2019'

  build_release_cpu_linux:
    name: CUDA Linux
    uses: ./.github/workflows/build-portable-release.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:ubuntu-22.04'

  build_release_macos:
    name: macOS 
    uses: ./.github/workflows/build-portable-release.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:macos-13'
